[features]
seeds = false
skip-lint = false
[programs.devnet]
my_project = "DqDyFiVXaHVe52NC6MjD4e1Ftks1UCHVoQnkAHViWwjX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jorocca/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
